# Java
javaVersion=21
projectVersion=0.0.1-SNAPSHOT

# Spring Boot
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7

# Dependencies
lombokVersion=1.18.38
testcontainersVersion=1.20.4

# Testing
jacocoVersion=0.8.12

# Build tooling
sonarqubePluginVersion=6.2.0.5505
spotlessVersion=8.9.0
owaspDependencyCheckVersion=12.2.2

# Build
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
